### ISSUE TITLE
name change request b/c of Docker guidelines

### ISSUE THREAD

**Issue by lasomethingsomething** [zalando/docker-ubuntu#12]
Requesting a name change in light of [this](https://www.andreas-jung.com/contents/dont-use-docker-in-github-repo-names-or-as-twitter-handle) and related email thread.

**Comment by ChristianLohmann** [comment]
same recommendation as everywhere: swap the parts -> `ubuntu-docker`

**Comment by lasomethingsomething** [comment]
@ChristianLohmann I've asked our legal team if this is true; don't want to risk it. Will let you know ASAP.

**Comment by lasomethingsomething** [comment]
Hey @ChristianLohmann -- I emailed internally a note from our Legal team on this; check it out. :)
