### ISSUE TITLE
Add AmazonRootCA1 to certificate store (/usr/local/share/ca-certificates)

### ISSUE THREAD

**Issue by kgalli** [zalando/docker-ubuntu#13]
If I'm not mistaken we do not have the Root CAs in the certificate store. But those are necessary if the certificate used is used by amazon (typically the case when certificate was created via AWS Certificate Manager).

Link to the root CAs: https://www.amazontrust.com/repository/.

**Comment by hjacobs** [comment]
That's not true, ACM certs are trusted by Ubuntu itself already --- please verify yourself with:

```
docker run -it registry.opensource.zalan.do/stups/ubuntu:16.04-52 curl https://myendpoint-with-acm-cert.example.org/
```
