### ISSUE TITLE
Update to Ubuntu 17.04

### ISSUE THREAD

**Issue by vroldanbet** [zalando/docker-ubuntu#19]
Ubuntu 17.04 is available for some time now. Let's update this docker image to use it.

**Comment by harti2006** [comment]
17.04 will be deprecated soon: https://www.ubuntu.com/info/release-end-of-life
Shouldn't we better wait for 18.04 LTS?

**Comment by vroldanbet** [comment]
@harti2006 yeah, I missed that :( I assumed 17.04 was LTS.

We should wait for 18.04, yes
