### ISSUE TITLE
Upgrade to Ubuntu 18.10

### ISSUE THREAD

**Issue by pheanex** [zalando/docker-ubuntu#24]
We need sqlite3.24 in stups/python => this will be only available with ubuntu 18.10 => Can we upgrade latest to ubuntu 18.10 although it is not LTS? Do we really need LTS? If so, why?

**Comment by szuecs** [comment]
:-1:

**Comment by szuecs** [comment]
it's not LTS, please compile the dependency yourself.

**Comment by hjacobs** [comment]
@szuecs comment sounds a little bit harsh, but yes, we will only support LTS releases for base images.
