### ISSUE TITLE
Push image to registry.opensource.zalan.do as well

### ISSUE THREAD

**Issue by sarnowski** [zalando/docker-ubuntu#5]
Public hub is just sooo slow

**Comment by hjacobs** [comment]
:+1:

**Comment by lasomethingsomething** [comment]
@hjacobs @sarnowski This issue's from November 2015. Do you still need to do this? If so, what about adding the "Help Wanted" label?

**Comment by hjacobs** [comment]
This is already done: https://registry.opensource.zalan.do/v2/stups/ubuntu/tags/list
