### ISSUE TITLE
purge.sh does not reduce image size?

### ISSUE THREAD

**Issue by mfellner** [zalando/docker-ubuntu#7]
Unfortunately, because Docker keeps the contents of previous image layers, the final image size is not reduced by deleting documentation.

Is there another reason for doing that? Otherwise we could get rid of purge.sh.

**Comment by hjacobs** [comment]
Actually we use `docker-squash` to reduce the final image size (it WILL remove deleted contents).

=> purge.sh makes sense :smile:

**Comment by hjacobs** [comment]
FYI: the command is:

```
 docker-squash -verbose -from root -t mytag | docker load
```

**Comment by hjacobs** [comment]
now mentioned here: https://github.com/zalando/docker-ubuntu/commit/a776a7e5299ba521edae79a8ec4a252bdac66388
